
SKIN = 0
MUSCLE = 500
BONES = 1000
DEEP_BONES = 1150

DEFAULT_REGIONS = [SKIN, MUSCLE, BONES, DEEP_BONES]

DEFAULT_ISO = 500

RED = 0
GREEN = 1
BLUE = 2

DEFAULT_SKIN = [0, 0, 0]
DEFAULT_MUSCLE = [100, 50, 30]
DEFAULT_BONES = [100, 50, 30]
DEFAULT_DEEP_BONES = [100, 100, 90]

DEFAULT_RGB = [DEFAULT_SKIN, DEFAULT_MUSCLE, DEFAULT_BONES, DEFAULT_DEEP_BONES]

DEFAULT_SKIN_OPACITY = 15
DEFAULT_MUSCLE_OPACITY = 30
DEFAULT_BONES_OPACITY = 45
DEFAULT_DEEP_BONES_OPACITY = 60

DEFAULT_OPACITY = [DEFAULT_SKIN_OPACITY, DEFAULT_MUSCLE_OPACITY, DEFAULT_BONES_OPACITY, DEFAULT_DEEP_BONES_OPACITY]